[package]
name = "kiwiyou-bot"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
lambda_http = "0.1"
lambda_runtime = "0.2"
lazy_static = "1.4.0"
serde_json = "1.0"
teloxide = "0.2"
tokio = "0.2"